# Configuration for Alacritty, the GPU enhanced terminal emulator.

# 导入额外的配置文件
#
# 按照列表顺序进行加载，如果文件不存在，那么会跳过。如果和先前导入的配置存在相同的字段，那么会被替换。
# 所有的 import 路径要么使用以 `/` 开头的绝对路径，要么以用户的 HOME 目录开头 `~/`
# import:
#  - /path/to/alacritty.yml

# ----------颜色设置----------- Afterglow主题
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f7061"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.normal]
black = "#384048"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#d0d0d0"
yellow = "#ffcb6b"

[colors.primary]
background = "#2c2c2c"
foreground = "#d0d0d0"

# --- 颜色设置完 ---------
# --- 光标配置 -----

    # 可以为下面的值:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam

[cursor.style]
shape = "Beam"

    # 光标闪烁状态
    #
    # 可以为下面的值:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
blinking = "On"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\f"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "transparent"

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 22
y = 22

[general]
live_config_reload = true
